# This file specifies options for running the DA code.
# Some options are listed in brackets

# Location of data directory
data_dir: '/projects/pd_lab/data/data_assimilation/'
lipd_dir: '/projects/pd_lab/mpe32/LiPD-utilities/Python/'  # If lipd isn't part of your python install, specify its location here.

# Primary options
time_resolution:        10          # The base temporal resolution, in years [10]
maximum_resolution:     1000        # The maximum temporal resolution for proxies, in years [1000]
prior_window:           5010        # The size of the window for the time-varying prior, in years [5010,1010,'all']
assimate_together:      True        # If False, assimile proxies one at a time (slower) [True,False]
localization_radius:    None        # Localization radius, in meters [None,15000]  Only works if assimate_together=False
resolution_band:        [None,None] # Only assimiate proxies with median resolutions in this band.
verbose_level:          0           # How much output to print to screen.  Higher numbers = more output.
assign_seasonality:     False       # If something other than false, all proxies are set to sepecific seasonalities [False,'annual','summer','winter']
uncertainty_multiplier: 1           # Adjust the proxy uncertainties by multiplying them by this value [1,0.5,etc.]
filename_mse:           None        # A file containing TSids and MSE values for each proxy.  [None,'path/to/file.txt']
percent_to_assimilate:  100         # What percentage of proxies to assimilate [100]
seed_for_proxy_choice:  0           # This seed in only used if 'percent_to_assimilate' is below 100 [0]

# Models for prior ['hadcm3','trace','gfdl_cm21_control','ipsl_control','hadcm3_regrid','trace_regrid','gfdl_cm21_control_regrid','ipsl_control_regrid']
models_for_prior: ['trace_regrid']

# Proxy datasets ['temp12k','pages2k','pages2k_screened']
proxy_datasets_to_assimilate: ['temp12k']

# Age ranges
age_range_to_reconstruct: [0,12000]
reference_period:         [0,5000]
age_range_model:          [0,22000]
